### PR TITLE
Invites & sharing Room URL use Web Share API if available

### PR DESCRIPTION
**Pull request by DougReeder**
Sharing is an additional option, when available. It works as expected on Firefox and Chrome on MacOS, Oculus Browser on Quest, Safari on iOS and Chrome on Android.  As noted earlier, many platforms only pass the URL to destination, or just the URL and title.

Implements #6507 

There's an image with this code on Docker Hub: dougreeder/hubsfirst:v1

### CODE REVIEW

**Comment by DougReeder** [comment]
Here's a screenshot of the new Share room link using the Web Share API.

Share room link

And here's one possibility of what might result
room link email

**Comment by DougReeder** [comment]
PinkPolygonSoup has said the wording is fine.

**Comment by DougReeder** [comment]
That completes the changes from today's dev meeting. Now that we have testing by other people, I think this is ready to go!

**Comment by Exairnous** [comment]
My apologies for the delay.  This looks good to me code and functionality-wise, but prettier complains when I run `npm run test` can you confirm/fix?  After that's done, I think this PR is good to merge.  Thank you very much for submitting this improvement :)

**Pull request merged**
